/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author luks
 */
public class TelaGerLivro extends javax.swing.JDialog {

    TelaPrinc telaP;
    

    
    public TelaGerLivro(TelaPrinc telaP) {
       
       ImageIcon icone = new ImageIcon(getClass().getResource("/Img/icone/icone.png"));
       this.setIconImage(icone.getImage()); 
       
        
        initComponents();
        
        bVoltar.setVerticalTextPosition(SwingConstants.BOTTOM);
        bVoltar.setHorizontalTextPosition(SwingConstants.CENTER);
        
        
        
         bEditarLivro.setVerticalTextPosition(SwingConstants.BOTTOM);
        bEditarLivro.setHorizontalTextPosition(SwingConstants.CENTER);
        
         bExcluir.setVerticalTextPosition(SwingConstants.BOTTOM);
        bExcluir.setHorizontalTextPosition(SwingConstants.CENTER);
        
        
        this.telaP = telaP;
        
        this.setLocationRelativeTo(null);
        this.setVisible(true);
        
        this.atualizaTabela();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bExcluir = new javax.swing.JButton();
        bEditarLivro = new javax.swing.JButton();
        bVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tPesquisar = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Gerenciar Acervo");
        setMinimumSize(new java.awt.Dimension(1044, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(26, 141, 189));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gerenciar Acervo");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(42, 42, 42)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 328, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(33, 33, 33)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(26, 141, 189));

        bExcluir.setContentAreaFilled(false);
        bExcluir.setFocusPainted(false);
        bExcluir.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bExcluir.setForeground(new java.awt.Color(240, 240, 240));
        bExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botoes/removerLivro2.png"))); // NOI18N
        bExcluir.setText("<html><center>Remover<br>Item");
        bExcluir.setBorderPainted(false);
        bExcluir.setContentAreaFilled(false);
        bExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bExcluirMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bExcluirMouseExited(evt);
            }
        });
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });

        bEditarLivro.setContentAreaFilled(false);
        bEditarLivro.setFocusPainted(false);
        bEditarLivro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bEditarLivro.setForeground(new java.awt.Color(240, 240, 240));
        bEditarLivro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botoes/editarLivro2.png"))); // NOI18N
        bEditarLivro.setText("<html><center>Editar<br>Item");
        bEditarLivro.setBorderPainted(false);
        bEditarLivro.setContentAreaFilled(false);
        bEditarLivro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bEditarLivroMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bEditarLivroMouseExited(evt);
            }
        });
        bEditarLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEditarLivroActionPerformed(evt);
            }
        });

        bVoltar.setContentAreaFilled(false);
        bVoltar.setFocusPainted(false);
        bVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bVoltar.setForeground(new java.awt.Color(240, 240, 240));
        bVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botoes/voltar.png"))); // NOI18N
        bVoltar.setText("<html><center>Voltar");
        bVoltar.setBorderPainted(false);
        bVoltar.setContentAreaFilled(false);
        bVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bVoltarMouseExited(evt);
            }
        });
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(bVoltar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(bEditarLivro, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(bExcluir, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(39, 39, 39)
                .add(bEditarLivro)
                .add(40, 40, 40)
                .add(bExcluir)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(bVoltar)
                .add(71, 71, 71))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Pesquisar item no acervo");

        tPesquisar.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tPesquisarActionPerformed(evt);
            }
        });
        tPesquisar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tPesquisarKeyReleased(evt);
            }
        });

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Num_Registro", "Titulo do Item", "Autor", "Categoria", "Data de Registro", "Editora", "Disponibilidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setMinWidth(60);
            jTable1.getColumnModel().getColumn(0).setMaxWidth(60);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(180);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(120);
            jTable1.getColumnModel().getColumn(5).setResizable(false);
        }

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(20, 20, 20)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 892, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tPesquisar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 448, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 238, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(91, 91, 91)
                .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .add(120, 120, 120)
                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(10, 10, 10)
                .add(tPesquisar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(9, 460, Short.MAX_VALUE))
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(120, 120, 120)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 361, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tPesquisarActionPerformed
    if(tPesquisar.getText().equals("")){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection conec;
            
            conec = DriverManager.getConnection("jdbc:mysql://127.0.0.1/biblioteca","root","");
            
            String query = "select * from livros ORDER BY titulo_livro ASC";
            
            PreparedStatement st = conec.prepareStatement(query);
            
           
            
            
            //Até aqui em cima, tudo igual a antes.
            
            //Agora, declarar o ResultSet, que vai pegar o resultado do BD
            
            ResultSet rs = st.executeQuery();
            
            //Agora, mostrar o resultado da pesquisa:
            
            
            
            
            //Mostrar na tabela:
            
            //Cria o modelo padrão da tabela:
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            
            model.setNumRows(0);
            
            while(rs.next()){
                
                
                //Cria o novo vetor delimitando o tamanho e valores por CHAVES { }
     model.addRow(new Object[]{rs.getString("codigo_livro"),rs.getString("num_reg"),rs.getString("titulo_livro"),rs.getString("nome_autor"),rs.getString("categoria"),rs.getString("data_cad"),rs.getString("editora"),rs.getString("disponibilidade")  });
                
               
              
            }
            
       
            
            
            
            
        } catch (ClassNotFoundException ex) {
            System.out.println("Não foi possivel encontrar o Driver");
        } catch (SQLException ex) {
            System.out.println("Erro ao conectar com o BD");
        }
         tPesquisar.setText("");
    }
           
        
       else{
        
        
       try {
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection conec;
            
            conec = DriverManager.getConnection("jdbc:mysql://127.0.0.1/biblioteca","root","");
            
            String query = "select * from livros where titulo_livro like ? or num_reg like ? or editora like ? or titulo_livro like ? or nome_autor like ? or data_cad like ? or categoria like ? ORDER BY titulo_livro ASC";
            
            PreparedStatement st = conec.prepareStatement(query);
            
            st.setString(1,"%"+tPesquisar.getText()+"%");
            st.setString(2,"%"+tPesquisar.getText()+"%");
            st.setString(3,"%"+tPesquisar.getText()+"%");
            st.setString(4,"%"+tPesquisar.getText()+"%");
            st.setString(5,"%"+tPesquisar.getText()+"%");
            st.setString(6,"%"+tPesquisar.getText()+"%");
            st.setString(7,"%"+tPesquisar.getText()+"%");
            
            
            //Até aqui em cima, tudo igual a antes.
            
            //Agora, declarar o ResultSet, que vai pegar o resultado do BD
            
            ResultSet rs = st.executeQuery();
            
            //Agora, mostrar o resultado da pesquisa:
            
            
            
            
            //Mostrar na tabela:
            
            //Cria o modelo padrão da tabela:
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            
            model.setNumRows(0);
            
            while(rs.next()){
                
                
                //Cria o novo vetor delimitando o tamanho e valores por CHAVES { }
               model.addRow(new Object[]{rs.getString("codigo_livro"),rs.getString("num_reg"),rs.getString("titulo_livro"),rs.getString("nome_autor"),rs.getString("categoria"),rs.getString("data_cad"),rs.getString("editora"),rs.getString("disponibilidade")  });
                
               
              
            }
            
            
            tPesquisar.setText("");
            
            
            
            
            
            
            
        } catch (ClassNotFoundException ex) {
            System.out.println("Não foi possivel encontrar o Driver");
        } catch (SQLException ex) {
            System.out.println("Erro ao conectar com o BD");
        }
       
       }
          
    }//GEN-LAST:event_tPesquisarActionPerformed

 
    
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      //  telaP.GerencLivroAberto = false;
        telaP.setEnabled(true);
        
        
    }//GEN-LAST:event_formWindowClosing

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed
  int linha = jTable1.getSelectedRow();
        if(linha == -1){         
           JOptionPane.showMessageDialog(null, "Por favor, selecione uma linha na tabela\npara completar essa ação.","Selecione uma linha",JOptionPane.INFORMATION_MESSAGE);
       }
        else{
        
        Object[] options = { "Sim", "Não" };  
this.setAlwaysOnTop(false);    
int op = JOptionPane.showOptionDialog(null,"Deseja realmente remover o item "+(String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 2)+" ?",  "Remover Item", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);  
this.setAlwaysOnTop(true);       
        if(op==0){
    
        //EXCLUI
        try {
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection conec;
            
            conec = DriverManager.getConnection("jdbc:mysql://127.0.0.1/biblioteca","root","");
            
            String query = "delete from livros where codigo_livro = ?";
            
            PreparedStatement st = conec.prepareStatement(query);
            
            String index = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0);
            
            st.setString(1,index);
            
            

            
           st.executeUpdate();
            

            st.close();
            conec.close();
            
            
            
       
            
        } catch (ClassNotFoundException ex) {
            System.out.println("Não foi possivel encontrar o Driver");
        } catch (SQLException ex) {
            System.out.println("Erro ao conectar com o BD");
        }

//Atualiza

try {
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection conec;
            
            conec = DriverManager.getConnection("jdbc:mysql://127.0.0.1/biblioteca","root","");
            
            String query = "select * from livros";
            
            PreparedStatement st = conec.prepareStatement(query);
            
           
            
            
            //Até aqui em cima, tudo igual a antes.
            
            //Agora, declarar o ResultSet, que vai pegar o resultado do BD
            
            ResultSet rs = st.executeQuery();
            
            //Agora, mostrar o resultado da pesquisa:
            
            
            
            
            //Mostrar na tabela:
            
            //Cria o modelo padrão da tabela:
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            
            model.setNumRows(0);
            
            while(rs.next()){
                
                
                //Cria o novo vetor delimitando o tamanho e valores por CHAVES { }
     model.addRow(new Object[]{rs.getString("codigo_livro"),rs.getString("num_reg"),rs.getString("titulo_livro"),rs.getString("nome_autor"),rs.getString("data_cad"),rs.getString("editora") });
                
               
              
            }
            
       
            
            
            
            
        } catch (ClassNotFoundException ex) {
            System.out.println("Não foi possivel encontrar o Driver");
        } catch (SQLException ex) {
            System.out.println("Erro ao conectar com o BD");
        }
        }
        

        }
       
    }//GEN-LAST:event_bExcluirActionPerformed

    public void atualizaTabela(){
          try {
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection conec;
            
            conec = DriverManager.getConnection("jdbc:mysql://127.0.0.1/biblioteca","root","");
            
            String query = "select * from livros ORDER BY titulo_livro ASC";
            
            PreparedStatement st = conec.prepareStatement(query);

            
            //Até aqui em cima, tudo igual a antes.
            
            //Agora, declarar o ResultSet, que vai pegar o resultado do BD
            
            ResultSet rs = st.executeQuery();
            
            //Agora, mostrar o resultado da pesquisa:
            
            
            
            
            //Mostrar na tabela:
            
            //Cria o modelo padrão da tabela:
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            
            model.setNumRows(0);
            
            while(rs.next()){
                
                
                //Cria o novo vetor delimitando o tamanho e valores por CHAVES { }
                model.addRow(new Object[]{rs.getString("codigo_livro"),rs.getString("num_reg"),rs.getString("titulo_livro"),rs.getString("nome_autor"),rs.getString("categoria"),rs.getString("data_cad"),rs.getString("editora"),rs.getString("disponibilidade") });
                
               //Mostra no console:
                //Campo (nome) do BD
               ;
            }
            
            
            
            
            
            
            
            
            
            
        } catch (ClassNotFoundException ex) {
            System.out.println("Não foi possivel encontrar o Driver");
        } catch (SQLException ex) {
            System.out.println("Erro ao conectar com o BD");
        }
    }
    
    
    
    private void bEditarLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEditarLivroActionPerformed
  int linha = jTable1.getSelectedRow();
        if(linha == -1){         
           JOptionPane.showMessageDialog(null, "Por favor, selecione uma linha na tabela\npara completar essa ação.","Selecione uma linha",JOptionPane.INFORMATION_MESSAGE);
       }
        else{       
       String codigo = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0);
       String numReg = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1);
       String titulo= (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 2);
       String autor = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 3);
       String editora = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 6);
           String quantidade = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 7);
       
       
       TelaEditLivro telaEditLivro = new TelaEditLivro(telaP,this,codigo,titulo,autor,numReg,editora,quantidade);
 this.setEnabled(false);
       this.setFocusable(false);
       
        }
    }//GEN-LAST:event_bEditarLivroActionPerformed

    private void bVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bVoltarMouseEntered
        bVoltar.setForeground(Color.black);
    }//GEN-LAST:event_bVoltarMouseEntered

    private void bVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bVoltarMouseExited
        bVoltar.setForeground(Color.white);
    }//GEN-LAST:event_bVoltarMouseExited

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        this.dispose();
        telaP.toFront();
        telaP.setEnabled(true);
    }//GEN-LAST:event_bVoltarActionPerformed

    private void bEditarLivroMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditarLivroMouseEntered
        bEditarLivro.setForeground(Color.black);
    }//GEN-LAST:event_bEditarLivroMouseEntered

    private void bEditarLivroMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bEditarLivroMouseExited
         bEditarLivro.setForeground(Color.white);
    }//GEN-LAST:event_bEditarLivroMouseExited

    private void bExcluirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bExcluirMouseEntered
         bExcluir.setForeground(Color.black);
    }//GEN-LAST:event_bExcluirMouseEntered

    private void bExcluirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bExcluirMouseExited
         bExcluir.setForeground(Color.white);
    }//GEN-LAST:event_bExcluirMouseExited

    private void tPesquisarKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tPesquisarKeyReleased
        if(tPesquisar.getText().equals("")){
        try {
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection conec;
            
            conec = DriverManager.getConnection("jdbc:mysql://127.0.0.1/biblioteca","root","");
            
            String query = "select * from livros ORDER BY titulo_livro ASC";
            
            PreparedStatement st = conec.prepareStatement(query);
            
           
            
            
            //Até aqui em cima, tudo igual a antes.
            
            //Agora, declarar o ResultSet, que vai pegar o resultado do BD
            
            ResultSet rs = st.executeQuery();
            
            //Agora, mostrar o resultado da pesquisa:
            
            
            
            
            //Mostrar na tabela:
            
            //Cria o modelo padrão da tabela:
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            
            model.setNumRows(0);
            
            while(rs.next()){
                
                
                //Cria o novo vetor delimitando o tamanho e valores por CHAVES { }
      model.addRow(new Object[]{rs.getString("codigo_livro"),rs.getString("num_reg"),rs.getString("titulo_livro"),rs.getString("nome_autor"),rs.getString("categoria"),rs.getString("data_cad"),rs.getString("editora"),rs.getString("disponibilidade")  });
                
               
              
            }
            
       
            
            
            
            
        } catch (ClassNotFoundException ex) {
            System.out.println("Não foi possivel encontrar o Driver");
        } catch (SQLException ex) {
            System.out.println("Erro ao conectar com o BD");
        }
         
    }
           
        
       else{
        
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
            
            Connection conec;
            
            conec = DriverManager.getConnection("jdbc:mysql://127.0.0.1/biblioteca","root","");
            
            String query = "select * from livros where titulo_livro like ? or num_reg like ? or editora like ? or titulo_livro like ? or nome_autor like ? or data_cad like ? or categoria like ? ORDER BY titulo_livro ASC";
            
            PreparedStatement st = conec.prepareStatement(query);
            
            st.setString(1,"%"+tPesquisar.getText()+"%");
            st.setString(2,"%"+tPesquisar.getText()+"%");
            st.setString(3,"%"+tPesquisar.getText()+"%");
            st.setString(4,"%"+tPesquisar.getText()+"%");
            st.setString(5,"%"+tPesquisar.getText()+"%");
            st.setString(6,"%"+tPesquisar.getText()+"%");
            st.setString(7,"%"+tPesquisar.getText()+"%");
            
            
            //Até aqui em cima, tudo igual a antes.
            
            //Agora, declarar o ResultSet, que vai pegar o resultado do BD
            
            ResultSet rs = st.executeQuery();
            
            //Agora, mostrar o resultado da pesquisa:
            
            
            
            
            //Mostrar na tabela:
            
            //Cria o modelo padrão da tabela:
            
            DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
            
            model.setNumRows(0);
            
            while(rs.next()){
                
                
                //Cria o novo vetor delimitando o tamanho e valores por CHAVES { }
               model.addRow(new Object[]{rs.getString("codigo_livro"),rs.getString("num_reg"),rs.getString("titulo_livro"),rs.getString("nome_autor"),rs.getString("categoria"),rs.getString("data_cad"),rs.getString("editora"),rs.getString("disponibilidade")  });
                
               
              
            }
            
            
            
            
            
            
            
            
            
            
        } catch (ClassNotFoundException ex) {
            System.out.println("Não foi possivel encontrar o Driver");
        } catch (SQLException ex) {
            System.out.println("Erro ao conectar com o BD");
        }
       
       }
    }//GEN-LAST:event_tPesquisarKeyReleased

    public void reabrirEdit() {                                             
       
          String codigo = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0);
       String numReg = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1);
       String titulo= (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 2);
       String autor = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 3);
       String editora = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 6);
           String quantidade = (String) jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 7);
       
       
       TelaEditLivro telaEditLivro = new TelaEditLivro(telaP,this,codigo,titulo,autor,numReg,editora,quantidade);
       telaEditLivro.toFront();
        
    }   
    
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bEditarLivro;
    private javax.swing.JButton bExcluir;
    private javax.swing.JButton bVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tPesquisar;
    // End of variables declaration//GEN-END:variables
}
