/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import MySQL.MySQL;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author luks
 */
public class TelaEditAluno extends javax.swing.JDialog {

    TelaPrinc telaP;
    String nome;
    String turma;
    String end;
    String tel;
    String codigo;
    TelaGerAluno telaGer;
    
    public TelaEditAluno(TelaPrinc telaP, TelaGerAluno telaGer,String codigo,String nome,String turma,String end,String tel) {
       ImageIcon icone = new ImageIcon(getClass().getResource("/Img/icone/icone.png"));
       this.setIconImage(icone.getImage()); 
       
       this.telaGer = telaGer;
       this.nome = nome;
       this.codigo = codigo;
       this.turma = turma;
       this.end = end;
       this.tel = tel;
       this.telaP = telaP;
       
       
       
        this.setResizable(false);
        
        initComponents();
        
        bLimpar.setVerticalTextPosition(SwingConstants.BOTTOM);
        bLimpar.setHorizontalTextPosition(SwingConstants.CENTER);
        
        bConcluiEd.setVerticalTextPosition(SwingConstants.BOTTOM);
        bConcluiEd.setHorizontalTextPosition(SwingConstants.CENTER);
        
        bCancelarEd.setVerticalTextPosition(SwingConstants.BOTTOM);
        bCancelarEd.setHorizontalTextPosition(SwingConstants.CENTER);
        
        
     tNome.setText(this.nome);
       tTurma.setText(this.turma);
       tEnd.setText(this.end);
       tTel.setText(this.tel);
        this.setVisible(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bLimpar = new javax.swing.JButton();
        bConcluiEd = new javax.swing.JButton();
        bCancelarEd = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        tTurma = new javax.swing.JTextField();
        tEnd = new javax.swing.JTextField();
        tTel = new javax.swing.JTextField();
        tNome = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Editar Leitor");
        setFocusCycleRoot(false);
        setMinimumSize(new java.awt.Dimension(846, 607));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(31, 126, 165));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Editar Leitor");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(42, 42, 42)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 328, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(476, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(33, 33, 33)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 846, 100);

        jPanel4.setBackground(new java.awt.Color(31, 126, 165));

        bLimpar.setContentAreaFilled(false);
        bLimpar.setFocusPainted(false);
        bLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bLimpar.setForeground(new java.awt.Color(240, 240, 240));
        bLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botoes/limparCampos2.png"))); // NOI18N
        bLimpar.setText("<html><center>Limpar<br>Campos");
        bLimpar.setBorderPainted(false);
        bLimpar.setContentAreaFilled(false);
        bLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bLimparMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bLimparMouseExited(evt);
            }
        });
        bLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparActionPerformed(evt);
            }
        });

        bConcluiEd.setContentAreaFilled(false);
        bConcluiEd.setFocusPainted(false);
        bConcluiEd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bConcluiEd.setForeground(new java.awt.Color(240, 240, 240));
        bConcluiEd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botoes/concluirEdicaoAluno2.png"))); // NOI18N
        bConcluiEd.setText("<html><center>Concluir<br>Edição");
        bConcluiEd.setBorderPainted(false);
        bConcluiEd.setContentAreaFilled(false);
        bConcluiEd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bConcluiEdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bConcluiEdMouseExited(evt);
            }
        });
        bConcluiEd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConcluiEdActionPerformed(evt);
            }
        });

        bCancelarEd.setContentAreaFilled(false);
        bCancelarEd.setFocusPainted(false);
        bCancelarEd.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bCancelarEd.setForeground(new java.awt.Color(240, 240, 240));
        bCancelarEd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botoes/cancelarEdicaoAluno2.png"))); // NOI18N
        bCancelarEd.setText("<html><center>Cancelar<br>Edição");
        bCancelarEd.setBorderPainted(false);
        bCancelarEd.setContentAreaFilled(false);
        bCancelarEd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bCancelarEdMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bCancelarEdMouseExited(evt);
            }
        });
        bCancelarEd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCancelarEdActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .add(10, 10, 10)
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(bConcluiEd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(bCancelarEd, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(bLimpar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(31, 31, 31)
                .add(bConcluiEd)
                .add(56, 56, 56)
                .add(bCancelarEd)
                .add(61, 61, 61)
                .add(bLimpar)
                .addContainerGap())
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 100, 100, 510);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Telefone");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(130, 420, 150, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nome do Leitor");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(130, 140, 150, 30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Turma");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(130, 230, 150, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Endereço");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(130, 320, 150, 30);

        tTurma.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTurmaActionPerformed(evt);
            }
        });
        jPanel1.add(tTurma);
        tTurma.setBounds(130, 270, 60, 30);

        tEnd.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tEnd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEndActionPerformed(evt);
            }
        });
        jPanel1.add(tEnd);
        tEnd.setBounds(130, 360, 550, 30);

        tTel.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tTel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTelActionPerformed(evt);
            }
        });
        jPanel1.add(tTel);
        tTel.setBounds(130, 460, 210, 30);

        tNome.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNomeActionPerformed(evt);
            }
        });
        jPanel1.add(tNome);
        tNome.setBounds(130, 180, 550, 30);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTurmaActionPerformed

    private void tEndActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEndActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tEndActionPerformed

    private void tTelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTelActionPerformed
          if(!tNome.getText().equals("")&&!tTurma.getText().equals("")&&!tEnd.getText().equals("")&&!tTel.getText().equals("")){
           MySQL sql = new MySQL();
           sql.editAluno(codigo,tNome.getText().toUpperCase(),tTurma.getText().toUpperCase(),tEnd.getText().toUpperCase(),tTel.getText().toUpperCase());
            tNome.setText("");
            tTurma.setText("");
            tEnd.setText("");
            tTel.setText("");
        //    this.setAlwaysOnTop(false);
           JOptionPane.showMessageDialog(null, "Aluno editado com sucesso!","Editar Aluno",JOptionPane.INFORMATION_MESSAGE);
        telaP.setEnabled(true);
          
           this.dispose();
           telaGer.atualizaTabela();
            telaGer.setEnabled(true);
           
            telaP.setEnabled(false);
            telaGer.toFront();
           
       }
       else{
        //   this.setAlwaysOnTop(false);
           JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos","Editar Aluno",JOptionPane.ERROR_MESSAGE);
        //   this.setAlwaysOnTop(true);
       }
    }//GEN-LAST:event_tTelActionPerformed

    private void tNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNomeActionPerformed

    private void bLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparActionPerformed
      
       
        tNome.setText("");
        tTurma.setText("");
        tEnd.setText("");
        tTel.setText("");
       
    }//GEN-LAST:event_bLimparActionPerformed

 
    
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      
        
   //      this.setAlwaysOnTop(false);
    Object[] options = { "Sim", "Não" };  
     int op = JOptionPane.showOptionDialog(null,"Deseja realmente cancelar a edição?",  "Cancelar Edição", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);  
       
        if(op==0){
            telaP.setEnabled(true);
            telaGer.setEnabled(true);
            
            this.dispose();
           
            telaP.setEnabled(false);
            
            telaGer.atualizaTabela();
           telaGer.toFront();
        }
        else{
         telaGer.reabrirEdit();
         telaGer.toFront();
         this.toFront();
        }
    
       
        
        
    }//GEN-LAST:event_formWindowClosing

    private void bConcluiEdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConcluiEdActionPerformed
          if(!tNome.getText().equals("")&&!tTurma.getText().equals("")&&!tEnd.getText().equals("")&&!tTel.getText().equals("")){
           MySQL sql = new MySQL();
           sql.editAluno(codigo,tNome.getText().toUpperCase(),tTurma.getText().toUpperCase(),tEnd.getText().toUpperCase(),tTel.getText().toUpperCase());
            tNome.setText("");
            tTurma.setText("");
            tEnd.setText("");
            tTel.setText("");
       //     this.setAlwaysOnTop(false);
           JOptionPane.showMessageDialog(null, "Aluno editado com sucesso!","Editar Aluno",JOptionPane.INFORMATION_MESSAGE);
         
           telaP.setEnabled(true);
          
           this.dispose();
           telaGer.atualizaTabela();
            telaGer.setEnabled(true);
           
            telaP.setEnabled(false);
            telaGer.toFront();
            
         //  telaGer.setAlwaysOnTop(true);
           
       }
       else{

          // this.setAlwaysOnTop(false);
           JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos","Editar Aluno",JOptionPane.ERROR_MESSAGE);
         //  this.setAlwaysOnTop(true);
       }
    }//GEN-LAST:event_bConcluiEdActionPerformed

    private void bCancelarEdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCancelarEdActionPerformed
      
     //  this.setAlwaysOnTop(false);
    Object[] options = { "Sim", "Não" };  
     int op = JOptionPane.showOptionDialog(null,"Deseja realmente cancelar a edição? Os dados antigos não serão alterados",  "Cancelar Edição", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);  
       
        if(op==0){
         
            telaP.setEnabled(true);
            telaGer.setEnabled(true);
            
            this.dispose();
           
            telaP.setEnabled(false);
            
            telaGer.atualizaTabela();
           
       //     telaGer.setEnabled(true);
           
        //   telaGer.setAlwaysOnTop(true);
        }
        else{
          //  this.setAlwaysOnTop(true);
        }
    
    
    }//GEN-LAST:event_bCancelarEdActionPerformed

    private void bConcluiEdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bConcluiEdMouseEntered
       bConcluiEd.setForeground(Color.black);
    }//GEN-LAST:event_bConcluiEdMouseEntered

    private void bConcluiEdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bConcluiEdMouseExited
         bConcluiEd.setForeground(Color.white);
    }//GEN-LAST:event_bConcluiEdMouseExited

    private void bCancelarEdMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancelarEdMouseEntered
         bCancelarEd.setForeground(Color.black);
    }//GEN-LAST:event_bCancelarEdMouseEntered

    private void bCancelarEdMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCancelarEdMouseExited
         bCancelarEd.setForeground(Color.white);
    }//GEN-LAST:event_bCancelarEdMouseExited

    private void bLimparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLimparMouseEntered
         bLimpar.setForeground(Color.black);
    }//GEN-LAST:event_bLimparMouseEntered

    private void bLimparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLimparMouseExited
        bLimpar.setForeground(Color.white);
    }//GEN-LAST:event_bLimparMouseExited

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCancelarEd;
    private javax.swing.JButton bConcluiEd;
    private javax.swing.JButton bLimpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField tEnd;
    private javax.swing.JTextField tNome;
    private javax.swing.JTextField tTel;
    private javax.swing.JTextField tTurma;
    // End of variables declaration//GEN-END:variables
}
