/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import MySQL.MySQL;
import java.awt.Color;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author luks
 */
public class TelaCadLivro extends javax.swing.JDialog {

    TelaPrinc telaP;
    String data;
    
    public TelaCadLivro(TelaPrinc telaP,String data) {
      ImageIcon icone = new ImageIcon(getClass().getResource("/Img/icone/icone.png"));
       this.setIconImage(icone.getImage()); 
        
       
        initComponents();
        
        bLimpar.setVerticalTextPosition(SwingConstants.BOTTOM);
        bLimpar.setHorizontalTextPosition(SwingConstants.CENTER);
        
        bVoltar.setVerticalTextPosition(SwingConstants.BOTTOM);
        bVoltar.setHorizontalTextPosition(SwingConstants.CENTER);
        
        bConfirma.setVerticalTextPosition(SwingConstants.BOTTOM);
        bConfirma.setHorizontalTextPosition(SwingConstants.CENTER);
        
        this.data = data;
        this.telaP = telaP;
        this.setVisible(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        bLimpar = new javax.swing.JButton();
        bConfirma = new javax.swing.JButton();
        bVoltar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tAutor = new javax.swing.JTextField();
        tTitulo = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tNumReg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tEditora = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tCategoria = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tQuantidade = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Adicionar ao Acervo");
        setMinimumSize(new java.awt.Dimension(847, 650));
        setPreferredSize(new java.awt.Dimension(847, 650));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1360, 1024));

        jPanel2.setBackground(new java.awt.Color(26, 141, 189));

        jLabel1.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Adicionar ao Acervo");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(42, 42, 42)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 328, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .add(33, 33, 33)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(26, 141, 189));
        jPanel4.setPreferredSize(new java.awt.Dimension(110, 673));

        bLimpar.setContentAreaFilled(false);
        bLimpar.setFocusPainted(false);
        bLimpar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bLimpar.setForeground(new java.awt.Color(240, 240, 240));
        bLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botoes/limparCampos2.png"))); // NOI18N
        bLimpar.setText("<html><center>Limpar<br>Campos");
        bLimpar.setBorderPainted(false);
        bLimpar.setContentAreaFilled(false);
        bLimpar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bLimparMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bLimparMouseExited(evt);
            }
        });
        bLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimparActionPerformed(evt);
            }
        });

        bConfirma.setContentAreaFilled(false);
        bConfirma.setFocusPainted(false);
        bConfirma.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bConfirma.setForeground(new java.awt.Color(240, 240, 240));
        bConfirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botoes/confirmarCadastroLivro2.png"))); // NOI18N
        bConfirma.setText("<html><center>Confirmar<br>Cadastro");
        bConfirma.setBorderPainted(false);
        bConfirma.setContentAreaFilled(false);
        bConfirma.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bConfirmaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bConfirmaMouseExited(evt);
            }
        });
        bConfirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bConfirmaActionPerformed(evt);
            }
        });

        bVoltar.setContentAreaFilled(false);
        bVoltar.setFocusPainted(false);
        bVoltar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bVoltar.setForeground(new java.awt.Color(240, 240, 240));
        bVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/botoes/voltar.png"))); // NOI18N
        bVoltar.setText("<html><center>Voltar");
        bVoltar.setBorderPainted(false);
        bVoltar.setContentAreaFilled(false);
        bVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bVoltarMouseExited(evt);
            }
        });
        bVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bVoltarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(bLimpar)
            .add(jPanel4Layout.createSequentialGroup()
                .add(bVoltar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
            .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel4Layout.createSequentialGroup()
                    .addContainerGap()
                    .add(bConfirma, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 80, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(31, Short.MAX_VALUE)))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .add(145, 145, 145)
                .add(bLimpar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(bVoltar)
                .add(56, 56, 56))
            .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                .add(jPanel4Layout.createSequentialGroup()
                    .add(31, 31, 31)
                    .add(bConfirma)
                    .addContainerGap(550, Short.MAX_VALUE)))
        );

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Título do Livro *");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Autor *");

        tAutor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tAutorActionPerformed(evt);
            }
        });

        tTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tTitulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tTituloActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Número de Registro *");

        tNumReg.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tNumReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tNumRegActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setText("Editora *");

        tEditora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tEditora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tEditoraActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("*Campos de preenchimento obrigatório");

        tCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-Selecione-", "Livro", "Revista", "Gibi", "Lista telefônica", "Outros" }));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setText("Categoria *");

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setText("Quantidade *");

        tQuantidade.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        tQuantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tQuantidadeActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(29, 29, 29)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(tTitulo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 530, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(tAutor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 530, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(tNumReg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 140, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(90, 90, 90)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tCategoria, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 167, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(tEditora, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 530, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 150, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, tQuantidade)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 512, Short.MAX_VALUE)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(40, 40, 40)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(10, 10, 10)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(tNumReg, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(tCategoria, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(29, 29, 29)
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(10, 10, 10)
                        .add(tTitulo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(10, 10, 10)
                        .add(tAutor, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(10, 10, 10)
                        .add(tEditora, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(10, 10, 10)
                        .add(tQuantidade, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 30, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 31, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 612, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(847, 650));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tAutorActionPerformed
      
        
    }//GEN-LAST:event_tAutorActionPerformed

    private void tTituloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tTituloActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tTituloActionPerformed

    private void bLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimparActionPerformed
      
        tQuantidade.setText("");
        tTitulo.setText("");
        tAutor.setText("");
        tEditora.setText("");
        tNumReg.setText("");
        
        
    
    }//GEN-LAST:event_bLimparActionPerformed

 
    
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
    //    telaP.CadLivroAberto = false;
        telaP.setEnabled(true);
        
        
    }//GEN-LAST:event_formWindowClosing

    private void bConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bConfirmaActionPerformed
       if(!tNumReg.getText().equals("") && !tAutor.getText().equals("") && !tTitulo.getText().equals("") && !tEditora.getText().equals("") && !tQuantidade.getText().equals("") && !tCategoria.getSelectedItem().toString().equals("-Selecione-") ){
           MySQL sql = new MySQL();
           sql.regLivro(tNumReg.getText().toUpperCase(),tTitulo.getText().toUpperCase(),tAutor.getText().toUpperCase(),data,tEditora.getText().toUpperCase(),tCategoria.getSelectedItem().toString().toUpperCase(), tQuantidade.getText() );
           tNumReg.setText("");
           tAutor.setText("");
           tNumReg.setText("");
           tTitulo.setText("");
           tEditora.setText("");
           tQuantidade.setText("");
           tCategoria.setSelectedIndex(0);
       //    this.setAlwaysOnTop(false);
           JOptionPane.showMessageDialog(null, "Item do acervo cadastrado com sucesso!","Adicionar ao Acervo",JOptionPane.INFORMATION_MESSAGE);
        //   this.setAlwaysOnTop(true);
       }
       else{
      //     this.setAlwaysOnTop(false);
           JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos","Adicionar ao Acervo",JOptionPane.ERROR_MESSAGE);
     //      this.setAlwaysOnTop(true);
       }
        
        tNumReg.requestFocus();
        
    }//GEN-LAST:event_bConfirmaActionPerformed

    private void tNumRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tNumRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tNumRegActionPerformed

    private void tEditoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tEditoraActionPerformed
       
    }//GEN-LAST:event_tEditoraActionPerformed

    private void bLimparMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLimparMouseEntered
       bLimpar.setForeground(Color.black);
    }//GEN-LAST:event_bLimparMouseEntered

    private void bLimparMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bLimparMouseExited
       bLimpar.setForeground(Color.white);
    }//GEN-LAST:event_bLimparMouseExited

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowClosed

    private void bVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bVoltarMouseEntered
        bVoltar.setForeground(Color.black);
    }//GEN-LAST:event_bVoltarMouseEntered

    private void bVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bVoltarMouseExited
        bVoltar.setForeground(Color.white);
    }//GEN-LAST:event_bVoltarMouseExited

    private void bVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bVoltarActionPerformed
        this.dispose();
        telaP.toFront();
        telaP.setEnabled(true);

    }//GEN-LAST:event_bVoltarActionPerformed

    private void bConfirmaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bConfirmaMouseEntered
        bConfirma.setForeground(Color.black);
    }//GEN-LAST:event_bConfirmaMouseEntered

    private void bConfirmaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bConfirmaMouseExited
         bConfirma.setForeground(Color.white);
    }//GEN-LAST:event_bConfirmaMouseExited

    private void tQuantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tQuantidadeActionPerformed
          if(!tNumReg.getText().equals("") && !tAutor.getText().equals("") && !tTitulo.getText().equals("") && !tEditora.getText().equals("") && !tQuantidade.getText().equals("") && !tCategoria.getSelectedItem().toString().equals("-Selecione-") ){
           MySQL sql = new MySQL();
           sql.regLivro(tNumReg.getText().toUpperCase(),tTitulo.getText().toUpperCase(),tAutor.getText().toUpperCase(),data,tEditora.getText().toUpperCase(),tCategoria.getSelectedItem().toString().toUpperCase(), tQuantidade.getText() );
           tNumReg.setText("");
           tAutor.setText("");
           tNumReg.setText("");
           tTitulo.setText("");
           tEditora.setText("");
           tQuantidade.setText("");
           tCategoria.setSelectedIndex(0);
       //    this.setAlwaysOnTop(false);
           JOptionPane.showMessageDialog(null, "Item do acervo cadastrado com sucesso!","Adicionar ao Acervo",JOptionPane.INFORMATION_MESSAGE);
        //   this.setAlwaysOnTop(true);
       }
       else{
      //     this.setAlwaysOnTop(false);
           JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos","Adicionar ao Acervo",JOptionPane.ERROR_MESSAGE);
     //      this.setAlwaysOnTop(true);
       }
        
        tNumReg.requestFocus();
    }//GEN-LAST:event_tQuantidadeActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bConfirma;
    private javax.swing.JButton bLimpar;
    private javax.swing.JButton bVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField tAutor;
    private javax.swing.JComboBox tCategoria;
    private javax.swing.JTextField tEditora;
    private javax.swing.JTextField tNumReg;
    private javax.swing.JTextField tQuantidade;
    private javax.swing.JTextField tTitulo;
    // End of variables declaration//GEN-END:variables
}
